# Generated by Django 4.2 on 2025-12-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['user', '-added_at'], name='watchlist_w_user_id_7df9b4_idx'),
        ),
    ]
